#!/usr/bin/env python3
"""Generate src/shared/IconPixelPack.luau from assets/images (64x64 RGBA base64).

Runtime fallback when cloud ASSET_IDS are 0 and asphalt rbxasset:// unavailable.
"""
from __future__ import annotations

import base64
import sys
from pathlib import Path

try:
	from PIL import Image
except ImportError as exc:  # pragma: no cover
	raise SystemExit("Pillow required: pip3 install Pillow") from exc

ROOT = Path(__file__).resolve().parents[2]
IMAGES = ROOT / "assets" / "images"
OUT = ROOT / "src" / "shared" / "IconPixelPack.luau"
SIZE = 64

# Logical key → PNG filename (store/game_icon/thumbnails excluded — Hub-only).
MAP = {
	"Hp": "icon_hp.png",
	"Atk": "icon_atk.png",
	"Gold": "icon_gold.png",
	"Level": "icon_level.png",
	"Crit": "icon_crit.png",
	"Reroll": "icon_reroll.png",
	"Restart": "icon_restart.png",
	"Transcend": "icon_transcend.png",
	"UpgradeMight": "upgrade_might.png",
	"UpgradeVitality": "upgrade_vitality.png",
	"BossKing": "boss_king.png",
	"PiecePawnBlue": "piece_pawn_blue.png",
	"PieceKnightBlue": "piece_knight_blue.png",
	"PieceBishopBlue": "piece_bishop_blue.png",
	"PieceRookBlue": "piece_rook_blue.png",
	"PieceQueenBlue": "piece_queen_blue.png",
	"PieceKingBlue": "piece_king_blue.png",
	"PiecePawnRed": "piece_pawn_red.png",
	"PieceKnightRed": "piece_knight_red.png",
	"PieceBishopRed": "piece_bishop_red.png",
	"PieceRookRed": "piece_rook_red.png",
	"PieceQueenRed": "piece_queen_red.png",
	"PieceKingRed": "piece_king_red.png",
}


def main() -> int:
	chunks = [
		"-- AUTO-GENERATED by scripts/assets/generate_icon_pixel_pack.py — do not edit.",
		"-- 64x64 RGBA raw pixels, base64. Runtime fallback (IconSurface / IconPixels).",
		"-- Prefer cloud ASSET_IDS or asphalt GeneratedAssets when available.",
		"local IconPixelPack = {",
		f"\twidth = {SIZE},",
		f"\theight = {SIZE},",
		"\tentries = {",
	]
	for key, name in MAP.items():
		path = IMAGES / name
		if not path.is_file():
			print(f"missing {path}", file=sys.stderr)
			return 1
		im = Image.open(path).convert("RGBA").resize((SIZE, SIZE), Image.Resampling.LANCZOS)
		b64 = base64.b64encode(im.tobytes()).decode("ascii")
		parts = [b64[i : i + 100] for i in range(0, len(b64), 100)]
		chunks.append(f"\t\t{key} = table.concat({{")
		for part in parts:
			chunks.append(f'\t\t\t"{part}",')
		chunks.append("\t\t}),")
	chunks += [
		"\t},",
		"}",
		"return IconPixelPack",
		"",
	]
	OUT.write_text("\n".join(chunks) + "\n", encoding="utf-8")
	print(f"generate_icon_pixel_pack: PASS out={OUT.relative_to(ROOT)} bytes={OUT.stat().st_size} keys={len(MAP)}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
